#!/bin/bash
set -e

export PATH="$HOME/.bun/bin:$PATH"

echo -e "\n✅ ### Starting Deploy... ###"
APP_DIR=/var/www/auto-grow-ui
GIT_DIR=/srv/git/auto-grow-ui.git
BRANCH="refs/heads/main"

while read oldrev newrev ref 
do
  if [ "$ref" = "$BRANCH" ]; then 
    echo "✅ Getting latest version..." 

    git --work-tree="$APP_DIR" \
        --git-dir="$GIT_DIR" \
        checkout -f main

    cd "$APP_DIR" 
    bun install

    echo "✅ Building..."

    pwd

    bun run build

    echo "✅ Restarting Server..."

    pm2 delete auto-grow-ui
    pm2 start "PORT=8080 bun /var/www/auto-grow-ui/dist/index.html" --name auto-grow-ui
    pm2 save 

    echo "🚀 Deployed Sucessfully..."
  fi
done