/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrackingRouteImport } from './routes/_authenticated/tracking'
import { Route as AuthenticatedStagesRouteImport } from './routes/_authenticated/stages'
import { Route as AuthenticatedProtocolsRouteImport } from './routes/_authenticated/protocols'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedActionsRouteImport } from './routes/_authenticated/actions'
import { Route as AuthenticatedTrackingIndexRouteImport } from './routes/_authenticated/tracking.index'
import { Route as AuthenticatedProtocolsIndexRouteImport } from './routes/_authenticated/protocols.index'
import { Route as AuthenticatedDevicesIndexRouteImport } from './routes/_authenticated/devices.index'
import { Route as AuthenticatedActionsIndexRouteImport } from './routes/_authenticated/actions.index'
import { Route as AuthenticatedTrackingTrackingIdRouteImport } from './routes/_authenticated/tracking.$trackingId'
import { Route as AuthenticatedActionsNewRouteImport } from './routes/_authenticated/actions.new'
import { Route as AuthenticatedProtocolsProtocolIdEditRouteImport } from './routes/_authenticated/protocols.$protocolId.edit'
import { Route as AuthenticatedDevicesDeviceIdEditRouteImport } from './routes/_authenticated/devices.$deviceId.edit'
import { Route as AuthenticatedActionsActionIdEditRouteImport } from './routes/_authenticated/actions.$actionId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrackingRoute = AuthenticatedTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStagesRoute = AuthenticatedStagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProtocolsRoute = AuthenticatedProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActionsRoute = AuthenticatedActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrackingIndexRoute =
  AuthenticatedTrackingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTrackingRoute,
  } as any)
const AuthenticatedProtocolsIndexRoute =
  AuthenticatedProtocolsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProtocolsRoute,
  } as any)
const AuthenticatedDevicesIndexRoute =
  AuthenticatedDevicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDevicesRoute,
  } as any)
const AuthenticatedActionsIndexRoute =
  AuthenticatedActionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedActionsRoute,
  } as any)
const AuthenticatedTrackingTrackingIdRoute =
  AuthenticatedTrackingTrackingIdRouteImport.update({
    id: '/$trackingId',
    path: '/$trackingId',
    getParentRoute: () => AuthenticatedTrackingRoute,
  } as any)
const AuthenticatedActionsNewRoute = AuthenticatedActionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedActionsRoute,
} as any)
const AuthenticatedProtocolsProtocolIdEditRoute =
  AuthenticatedProtocolsProtocolIdEditRouteImport.update({
    id: '/$protocolId/edit',
    path: '/$protocolId/edit',
    getParentRoute: () => AuthenticatedProtocolsRoute,
  } as any)
const AuthenticatedDevicesDeviceIdEditRoute =
  AuthenticatedDevicesDeviceIdEditRouteImport.update({
    id: '/$deviceId/edit',
    path: '/$deviceId/edit',
    getParentRoute: () => AuthenticatedDevicesRoute,
  } as any)
const AuthenticatedActionsActionIdEditRoute =
  AuthenticatedActionsActionIdEditRouteImport.update({
    id: '/$actionId/edit',
    path: '/$actionId/edit',
    getParentRoute: () => AuthenticatedActionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/actions': typeof AuthenticatedActionsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRouteWithChildren
  '/protocols': typeof AuthenticatedProtocolsRouteWithChildren
  '/stages': typeof AuthenticatedStagesRoute
  '/tracking': typeof AuthenticatedTrackingRouteWithChildren
  '/actions/new': typeof AuthenticatedActionsNewRoute
  '/tracking/$trackingId': typeof AuthenticatedTrackingTrackingIdRoute
  '/actions/': typeof AuthenticatedActionsIndexRoute
  '/devices/': typeof AuthenticatedDevicesIndexRoute
  '/protocols/': typeof AuthenticatedProtocolsIndexRoute
  '/tracking/': typeof AuthenticatedTrackingIndexRoute
  '/actions/$actionId/edit': typeof AuthenticatedActionsActionIdEditRoute
  '/devices/$deviceId/edit': typeof AuthenticatedDevicesDeviceIdEditRoute
  '/protocols/$protocolId/edit': typeof AuthenticatedProtocolsProtocolIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/stages': typeof AuthenticatedStagesRoute
  '/actions/new': typeof AuthenticatedActionsNewRoute
  '/tracking/$trackingId': typeof AuthenticatedTrackingTrackingIdRoute
  '/actions': typeof AuthenticatedActionsIndexRoute
  '/devices': typeof AuthenticatedDevicesIndexRoute
  '/protocols': typeof AuthenticatedProtocolsIndexRoute
  '/tracking': typeof AuthenticatedTrackingIndexRoute
  '/actions/$actionId/edit': typeof AuthenticatedActionsActionIdEditRoute
  '/devices/$deviceId/edit': typeof AuthenticatedDevicesDeviceIdEditRoute
  '/protocols/$protocolId/edit': typeof AuthenticatedProtocolsProtocolIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/actions': typeof AuthenticatedActionsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRouteWithChildren
  '/_authenticated/protocols': typeof AuthenticatedProtocolsRouteWithChildren
  '/_authenticated/stages': typeof AuthenticatedStagesRoute
  '/_authenticated/tracking': typeof AuthenticatedTrackingRouteWithChildren
  '/_authenticated/actions/new': typeof AuthenticatedActionsNewRoute
  '/_authenticated/tracking/$trackingId': typeof AuthenticatedTrackingTrackingIdRoute
  '/_authenticated/actions/': typeof AuthenticatedActionsIndexRoute
  '/_authenticated/devices/': typeof AuthenticatedDevicesIndexRoute
  '/_authenticated/protocols/': typeof AuthenticatedProtocolsIndexRoute
  '/_authenticated/tracking/': typeof AuthenticatedTrackingIndexRoute
  '/_authenticated/actions/$actionId/edit': typeof AuthenticatedActionsActionIdEditRoute
  '/_authenticated/devices/$deviceId/edit': typeof AuthenticatedDevicesDeviceIdEditRoute
  '/_authenticated/protocols/$protocolId/edit': typeof AuthenticatedProtocolsProtocolIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/actions'
    | '/dashboard'
    | '/devices'
    | '/protocols'
    | '/stages'
    | '/tracking'
    | '/actions/new'
    | '/tracking/$trackingId'
    | '/actions/'
    | '/devices/'
    | '/protocols/'
    | '/tracking/'
    | '/actions/$actionId/edit'
    | '/devices/$deviceId/edit'
    | '/protocols/$protocolId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/stages'
    | '/actions/new'
    | '/tracking/$trackingId'
    | '/actions'
    | '/devices'
    | '/protocols'
    | '/tracking'
    | '/actions/$actionId/edit'
    | '/devices/$deviceId/edit'
    | '/protocols/$protocolId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/actions'
    | '/_authenticated/dashboard'
    | '/_authenticated/devices'
    | '/_authenticated/protocols'
    | '/_authenticated/stages'
    | '/_authenticated/tracking'
    | '/_authenticated/actions/new'
    | '/_authenticated/tracking/$trackingId'
    | '/_authenticated/actions/'
    | '/_authenticated/devices/'
    | '/_authenticated/protocols/'
    | '/_authenticated/tracking/'
    | '/_authenticated/actions/$actionId/edit'
    | '/_authenticated/devices/$deviceId/edit'
    | '/_authenticated/protocols/$protocolId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tracking': {
      id: '/_authenticated/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AuthenticatedTrackingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stages': {
      id: '/_authenticated/stages'
      path: '/stages'
      fullPath: '/stages'
      preLoaderRoute: typeof AuthenticatedStagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/protocols': {
      id: '/_authenticated/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof AuthenticatedProtocolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/actions': {
      id: '/_authenticated/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof AuthenticatedActionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracking/': {
      id: '/_authenticated/tracking/'
      path: '/'
      fullPath: '/tracking/'
      preLoaderRoute: typeof AuthenticatedTrackingIndexRouteImport
      parentRoute: typeof AuthenticatedTrackingRoute
    }
    '/_authenticated/protocols/': {
      id: '/_authenticated/protocols/'
      path: '/'
      fullPath: '/protocols/'
      preLoaderRoute: typeof AuthenticatedProtocolsIndexRouteImport
      parentRoute: typeof AuthenticatedProtocolsRoute
    }
    '/_authenticated/devices/': {
      id: '/_authenticated/devices/'
      path: '/'
      fullPath: '/devices/'
      preLoaderRoute: typeof AuthenticatedDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedDevicesRoute
    }
    '/_authenticated/actions/': {
      id: '/_authenticated/actions/'
      path: '/'
      fullPath: '/actions/'
      preLoaderRoute: typeof AuthenticatedActionsIndexRouteImport
      parentRoute: typeof AuthenticatedActionsRoute
    }
    '/_authenticated/tracking/$trackingId': {
      id: '/_authenticated/tracking/$trackingId'
      path: '/$trackingId'
      fullPath: '/tracking/$trackingId'
      preLoaderRoute: typeof AuthenticatedTrackingTrackingIdRouteImport
      parentRoute: typeof AuthenticatedTrackingRoute
    }
    '/_authenticated/actions/new': {
      id: '/_authenticated/actions/new'
      path: '/new'
      fullPath: '/actions/new'
      preLoaderRoute: typeof AuthenticatedActionsNewRouteImport
      parentRoute: typeof AuthenticatedActionsRoute
    }
    '/_authenticated/protocols/$protocolId/edit': {
      id: '/_authenticated/protocols/$protocolId/edit'
      path: '/$protocolId/edit'
      fullPath: '/protocols/$protocolId/edit'
      preLoaderRoute: typeof AuthenticatedProtocolsProtocolIdEditRouteImport
      parentRoute: typeof AuthenticatedProtocolsRoute
    }
    '/_authenticated/devices/$deviceId/edit': {
      id: '/_authenticated/devices/$deviceId/edit'
      path: '/$deviceId/edit'
      fullPath: '/devices/$deviceId/edit'
      preLoaderRoute: typeof AuthenticatedDevicesDeviceIdEditRouteImport
      parentRoute: typeof AuthenticatedDevicesRoute
    }
    '/_authenticated/actions/$actionId/edit': {
      id: '/_authenticated/actions/$actionId/edit'
      path: '/$actionId/edit'
      fullPath: '/actions/$actionId/edit'
      preLoaderRoute: typeof AuthenticatedActionsActionIdEditRouteImport
      parentRoute: typeof AuthenticatedActionsRoute
    }
  }
}

interface AuthenticatedActionsRouteChildren {
  AuthenticatedActionsNewRoute: typeof AuthenticatedActionsNewRoute
  AuthenticatedActionsIndexRoute: typeof AuthenticatedActionsIndexRoute
  AuthenticatedActionsActionIdEditRoute: typeof AuthenticatedActionsActionIdEditRoute
}

const AuthenticatedActionsRouteChildren: AuthenticatedActionsRouteChildren = {
  AuthenticatedActionsNewRoute: AuthenticatedActionsNewRoute,
  AuthenticatedActionsIndexRoute: AuthenticatedActionsIndexRoute,
  AuthenticatedActionsActionIdEditRoute: AuthenticatedActionsActionIdEditRoute,
}

const AuthenticatedActionsRouteWithChildren =
  AuthenticatedActionsRoute._addFileChildren(AuthenticatedActionsRouteChildren)

interface AuthenticatedDevicesRouteChildren {
  AuthenticatedDevicesIndexRoute: typeof AuthenticatedDevicesIndexRoute
  AuthenticatedDevicesDeviceIdEditRoute: typeof AuthenticatedDevicesDeviceIdEditRoute
}

const AuthenticatedDevicesRouteChildren: AuthenticatedDevicesRouteChildren = {
  AuthenticatedDevicesIndexRoute: AuthenticatedDevicesIndexRoute,
  AuthenticatedDevicesDeviceIdEditRoute: AuthenticatedDevicesDeviceIdEditRoute,
}

const AuthenticatedDevicesRouteWithChildren =
  AuthenticatedDevicesRoute._addFileChildren(AuthenticatedDevicesRouteChildren)

interface AuthenticatedProtocolsRouteChildren {
  AuthenticatedProtocolsIndexRoute: typeof AuthenticatedProtocolsIndexRoute
  AuthenticatedProtocolsProtocolIdEditRoute: typeof AuthenticatedProtocolsProtocolIdEditRoute
}

const AuthenticatedProtocolsRouteChildren: AuthenticatedProtocolsRouteChildren =
  {
    AuthenticatedProtocolsIndexRoute: AuthenticatedProtocolsIndexRoute,
    AuthenticatedProtocolsProtocolIdEditRoute:
      AuthenticatedProtocolsProtocolIdEditRoute,
  }

const AuthenticatedProtocolsRouteWithChildren =
  AuthenticatedProtocolsRoute._addFileChildren(
    AuthenticatedProtocolsRouteChildren,
  )

interface AuthenticatedTrackingRouteChildren {
  AuthenticatedTrackingTrackingIdRoute: typeof AuthenticatedTrackingTrackingIdRoute
  AuthenticatedTrackingIndexRoute: typeof AuthenticatedTrackingIndexRoute
}

const AuthenticatedTrackingRouteChildren: AuthenticatedTrackingRouteChildren = {
  AuthenticatedTrackingTrackingIdRoute: AuthenticatedTrackingTrackingIdRoute,
  AuthenticatedTrackingIndexRoute: AuthenticatedTrackingIndexRoute,
}

const AuthenticatedTrackingRouteWithChildren =
  AuthenticatedTrackingRoute._addFileChildren(
    AuthenticatedTrackingRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedActionsRoute: typeof AuthenticatedActionsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRouteWithChildren
  AuthenticatedProtocolsRoute: typeof AuthenticatedProtocolsRouteWithChildren
  AuthenticatedStagesRoute: typeof AuthenticatedStagesRoute
  AuthenticatedTrackingRoute: typeof AuthenticatedTrackingRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActionsRoute: AuthenticatedActionsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRouteWithChildren,
  AuthenticatedProtocolsRoute: AuthenticatedProtocolsRouteWithChildren,
  AuthenticatedStagesRoute: AuthenticatedStagesRoute,
  AuthenticatedTrackingRoute: AuthenticatedTrackingRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
